name: CI
on:
  push:
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
      - uses: actions/checkout@v1
      - run: yarn install
      - run: yarn run build
      - uses: ./
      - run: cd test-build && sbt run
        shell: bash
  custom-url:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: yarn install
      - run: yarn run build
      - uses: ./
        with:
          java-version: graal@20.2.0=tgz+https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-20.2.0/graalvm-ce-java11-linux-amd64-20.2.0.tar.gz
      - run: cd test-build && sbt run
        shell: bash
